import type { Metadata } from 'next'
import './globals.css'
import { inter } from '@/lib/font'
import Script from 'next/script'

export const metadata: Metadata = {
    title: 'Iyah Store',
    description: 'Generated by iyah store application',
    icons: {
        icon: '/favicon.ico',
    },
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                {children}
                <Script
                    src="https://app.sandbox.midtrans.com/snap/snap.js"
                    data-client-key={
                        process.env.NEXT_PUBLIC_MIDTRANS_CLIENT_KEY
                    }
                    strategy="afterInteractive"
                />
            </body>
        </html>
    )
}
